version: "3.8"
services:
  mysql:
    image: mysql:latest
    container_name:  "${COMPOSE_PROJECT_NAME}_mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=Test@123
      - MYSQL_DATABASE=BankDB
    volumes:
      - main-bankapp-volume:/var/lib/mysql
    networks:
      - main-bankapp
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    ports:
      - "3306:3306"

  mainapp:
    image: pakeeza/javaspringboot-bankapp
    container_name: "${COMPOSE_PROJECT_NAME}_app"
    environment:
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/BankDB?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_PASSWORD=Test@123
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - main-bankapp
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  main-bankapp:

volumes:
    main-bankapp-volume:
